repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--verbose"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: ["--fix"]