[tool.poetry]
name = "earthsounds-obspy"
version = "0.5.0"
description = "Producer for generting and parsing raw earthquake data"
authors = ["Selwyn-Lloyd McPherson <selwyn.mcpherson@gmail.com>"]
readme = "README.md"

[tool.black]
line-length = 116

[tool.poetry.dependencies]
python = "^3.11"
obspy = "^1.4.1"
kafka-python = "^2.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
